import http.client

conn = http.client.HTTPConnection("theekshanas.auth0.com")

headers = { 'authorization': "Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6Ik1qaENNa1JCTWtSQk1qWTRNelE0T0RJeU0wSTNSRVV5UkVZME9VUXdOME0xT0RaRE9EYzRNUSJ9.eyJpc3MiOiJodHRwczovL3RoZWVrc2hhbmFzLmF1dGgwLmNvbS8iLCJzdWIiOiJtbUt4c2F5d241TmRMM1F2aklnWmUydmxMaGxYek93bUBjbGllbnRzIiwiYXVkIjoiaHR0cHM6Ly9vbmxpbmUtZXhhbS5zYW5zLmNvbS5iciIsImlhdCI6MTUyNDIwNTUzMywiZXhwIjoxNTI0MjkxOTMzLCJhenAiOiJtbUt4c2F5d241TmRMM1F2aklnWmUydmxMaGxYek93bSIsImd0eSI6ImNsaWVudC1jcmVkZW50aWFscyJ9.SpS8KkWCHBI_CGDZPpZ6vy5ijk82Fvr9HznqTAwD6squheIgy6LG2X7lcjkdDnQKq-esNYXfn6r-QZjgGHcZgWuCDiSV_XURmdm9PTKtokcjGPs3F1DanQja7qSCn82jWlnNHiy5xSpW5PBFPfLuH8RMQMEgFRfK6vSPkfVpXYGpDCPdY6zzJ5vomIMeUVzGN9TdlM6-UOaF_wMnvjsLCX5y9mSEujZf9rB3h4qvGXww6DJMSVbUegmY2eFHuiaQvEEeJQQg7EbHz9jFfNMNcZu2B1-jIm9W6ZjUaXvKTGva7zD0GUemPWhNMLlnnt7edJiTfgNuIBNkUGqoG5pNvA" }

conn.request("GET", "/", headers=headers)

res = conn.getresponse()
data = res.read()

print(data.decode("utf-8"))